//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie1new
    {
        public int Movie_ID { get; set; }
        public string Movie_Name { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public Nullable<System.TimeSpan> Movie_Length { get; set; }
        public string Languages { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    }
}
