//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movienew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movienew()
        {
            this.Shownew = new HashSet<Shownew>();
            this.ticketnew = new HashSet<ticketnew>();
        }
    
        public int Mid { get; set; }
        public string mname { get; set; }
        public string genre { get; set; }
        public string Director { get; set; }
        public string languages { get; set; }
        public Nullable<System.TimeSpan> length { get; set; }
        public Nullable<System.DateTime> Releasedate { get; set; }
        public Nullable<int> theatreid { get; set; }
    
        public virtual Theatrenew Theatrenew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shownew> Shownew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketnew> ticketnew { get; set; }
    }
}
