//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NetBanking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NetBanking()
        {
            this.Transacts = new HashSet<Transact>();
        }
    
        public int Netbankingid { get; set; }
        [Required(ErrorMessage = "Id is Required")]
        [DisplayName("Card Number:")]
        public Nullable<long> CardNumber { get; set; }
        [DisplayName("Name:")]
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }
        [DisplayName("CVV:")]
        [DataType("Password")]
        [Required(ErrorMessage = "CVV is Required")]

        public Nullable<int> CVV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transact> Transacts { get; set; }
    }
}
