//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineMovieTicketEntities14 : DbContext
    {
        public OnlineMovieTicketEntities14()
            : base("name=OnlineMovieTicketEntities14")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NetBanking> NetBankings { get; set; }
        public virtual DbSet<Transact> Transacts { get; set; }
        public virtual DbSet<UPI> UPIs { get; set; }
    }
}
