//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUDoperations.Context
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class student
    {
		[Required(ErrorMessage = "Required")]
		public string sname { get; set; }
        public int age { get; set; }
		[Required(ErrorMessage = "Required")]

		public string course { get; set; }
        public string city { get; set; }
		public int cid { get; set; }
        public int sid { get; set; }
    }
}
