//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shownew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shownew()
        {
            this.ticketnew = new HashSet<ticketnew>();
        }
    
        public int sid { get; set; }
        public Nullable<System.TimeSpan> starttime { get; set; }
        public Nullable<System.TimeSpan> endtime { get; set; }
        public Nullable<int> seatid { get; set; }
        public string showname { get; set; }
        public Nullable<int> movieid { get; set; }
        public Nullable<int> Theatreid { get; set; }
        public Nullable<int> Screenid { get; set; }
    
        public virtual Movienew Movienew { get; set; }
        public virtual Screennew Screennew { get; set; }
        public virtual SeatType1 SeatType1 { get; set; }
        public virtual Theatrenew Theatrenew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketnew> ticketnew { get; set; }
    }
}
