//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string DatofBirth { get; set; }
        public string Tickets { get; set; }
        public string ContactNo { get; set; }
    }
}
